# Generated by Django 6.0.6 on 2026-07-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Couleur')),
                ('code_hex', models.CharField(max_length=7, verbose_name='Code Hex (ex: #FF0000)')),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite', models.CharField(max_length=20, unique=True, verbose_name='Capacité RAM')),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAM',
                'ordering': ['capacite'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite', models.CharField(max_length=20, unique=True, verbose_name='Capacité Stockage')),
            ],
            options={
                'verbose_name': 'Stockage',
                'verbose_name_plural': 'Stockages',
                'ordering': ['capacite'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('caracteristiques', models.JSONField(blank=True, default=dict, help_text='Ex: {"ecran": "6.1 pouces", "processeur": "Snapdragon 8 Gen 2", "batterie": "3900 mAh"}', verbose_name='Caractéristiques techniques')),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('occasion', 'Occasion')], default='neuf', max_length=10, verbose_name='État')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='shop.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/', verbose_name='Image')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU (référence interne)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='shop.color', verbose_name='Couleur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='shop.product', verbose_name='Produit')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='shop.ram', verbose_name='RAM')),
                ('stockage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='shop.storage', verbose_name='Stockage')),
            ],
            options={
                'verbose_name': 'Variante produit',
                'verbose_name_plural': 'Variantes produit',
                'ordering': ['produit', 'couleur', 'ram', 'stockage'],
                'unique_together': {('produit', 'couleur', 'ram', 'stockage')},
            },
        ),
    ]
