# Generated by Django 6.0.6 on 2026-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du kit')),
                ('description', models.TextField(blank=True, verbose_name='Description du kit')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kits/', verbose_name='Image')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total (FCFA)')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produits', models.ManyToManyField(related_name='kits', to='shop.product', verbose_name='Produits du kit')),
            ],
            options={
                'verbose_name': 'Kit de produits',
                'verbose_name_plural': 'Kits de produits',
                'db_table': 'kits',
                'ordering': ['-created_at'],
            },
        ),
    ]
