# Generated by Django 6.0.6 on 2026-07-03 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_kit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_reception', models.CharField(choices=[('livraison', 'Livraison'), ('expedition', 'Expédition')], max_length=20, verbose_name='Mode de réception')),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('paye', 'Payé'), ('accepte', 'Accepté'), ('en_preparation', 'En préparation'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_attente_paiement', max_length=30, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('adresse_complete', models.TextField(verbose_name='Adresse complète')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire / Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_livraison', to='shop.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Adresse de livraison',
                'verbose_name_plural': 'Adresses de livraison',
                'db_table': 'adresses_livraison',
            },
        ),
        migrations.CreateModel(
            name='AdresseExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_expedition', to='shop.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': "Adresse d'expédition",
                'verbose_name_plural': "Adresses d'expédition",
                'db_table': 'adresses_expedition',
            },
        ),
        migrations.CreateModel(
            name='LivraisonOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Commande')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.productvariant', verbose_name='Variante produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Panier')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.productvariant', verbose_name='Variante produit')),
            ],
            options={
                'verbose_name': 'Article de panier',
                'verbose_name_plural': 'Articles de panier',
                'unique_together': {('cart', 'variante')},
            },
        ),
    ]
