# Generated by Django 6.0.6 on 2026-07-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0003_cart_order_adresselivraison_adresseexpedition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID de la cible')),
                ('type_reduction', models.CharField(choices=[('pourcentage', 'Pourcentage (%)'), ('montant', 'Montant fixe (FCFA)')], max_length=20, verbose_name='Type de réduction')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur de la réduction')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('statut', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('productvariant', 'kit')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de cible')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions',
                'ordering': ['-created_at'],
            },
        ),
    ]
