# Generated by Django 6.0.6 on 2026-07-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('especes', 'Espèces (à la livraison)')], default='mobile_money', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut du paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text="ID renvoyé par l'API de paiement", max_length=100, null=True, verbose_name='ID de transaction'),
        ),
    ]
