# Generated by Django 6.0.6 on 2026-07-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='ram',
            field=models.CharField(blank=True, choices=[('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('12 GB', '12 GB'), ('16 GB', '16 GB'), ('24 GB', '24 GB'), ('32 GB', '32 GB')], max_length=20, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stockage',
            field=models.CharField(blank=True, choices=[('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB')], max_length=20, null=True, verbose_name='Stockage'),
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
