# Generated by Django 6.0.6 on 2026-07-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productvariant_ram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Marque')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='shop.brand', verbose_name='Marque'),
        ),
    ]
