# Generated by Django 6.0.6 on 2026-07-05 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_brand_alter_product_marque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='produits',
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.kit', verbose_name='Kit')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='shop.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Article du kit',
                'verbose_name_plural': 'Articles du kit',
                'unique_together': {('kit', 'variante')},
            },
        ),
    ]
