# Generated by Django 6.0.6 on 2026-07-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0008_remove_kit_produits_kititem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variante',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('productvariant', 'kit')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Type d'article"),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'article"),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('productvariant', 'kit')}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name="Type d'article"),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'article"),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variante',
        ),
    ]
