# Generated by Django 6.0.6 on 2026-07-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0009_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('productvariant', 'kit')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Type d'article"),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name="ID de l'article"),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('productvariant', 'kit')}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name="Type d'article"),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name="ID de l'article"),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'content_type', 'object_id')},
        ),
    ]
