# Generated by Django 6.0.6 on 2026-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='marques', to='shop.category', verbose_name='Catégories'),
        ),
    ]
