# Generated by Django 6.0.6 on 2026-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_brand_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='taille_ecran',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Taille de l'écran"),
        ),
    ]
