# Generated by Django 6.0.6 on 2026-07-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productvariant_taille_ecran'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='resolution',
            field=models.CharField(blank=True, choices=[('LED', 'LED'), ('QLED', 'QLED'), ('OLED', 'OLED'), ('Mini LED', 'Mini LED'), ('LCD', 'LCD'), ('Neo QLED', 'Neo QLED')], max_length=50, null=True, verbose_name='Résolution / Technologie'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='couleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='shop.color', verbose_name='Couleur'),
        ),
    ]
