# Generated by Django 6.0.6 on 2026-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productvariant_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='technologie',
            field=models.CharField(blank=True, choices=[('lcd', 'LCD'), ('led', 'LED'), ('qled', 'QLED'), ('oled', 'OLED'), ('mini_led', 'Mini-LED'), ('micro_led', 'Micro-LED')], max_length=50, null=True, verbose_name='Technologie'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='resolution',
            field=models.CharField(blank=True, choices=[('hd', 'HD (1366x768)'), ('full_hd', 'Full HD (1920x1080)'), ('4k', '4K Ultra HD (3840x2160)'), ('8k', '8K (7680x4320)')], max_length=50, null=True, verbose_name='Résolution'),
        ),
    ]
