# Generated by Django 6.0.6 on 2026-07-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productvariant_technologie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo de la marque'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image'),
        ),
    ]
