# Generated by Django 6.0.6 on 2026-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_brand_logo_alter_kit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='technologie',
            field=models.CharField(blank=True, choices=[('lcd', 'LCD'), ('led', 'LED'), ('qled', 'QLED'), ('oled', 'OLED'), ('mini_led', 'Mini-LED'), ('micro_led', 'Micro-LED'), ('qd_mini_led', 'QD-Mini LED'), ('sqd_mini_led', 'SQD-Mini LED')], max_length=50, null=True, verbose_name='Technologie'),
        ),
    ]
