# Generated by Django 6.0.6 on 2026-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_productvariant_technologie'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='taux_rafraichissement',
            field=models.CharField(blank=True, choices=[('50hz', '50 Hz'), ('60hz', '60 Hz'), ('100hz', '100 Hz'), ('120hz', '120 Hz'), ('144hz', '144 Hz'), ('240hz', '240 Hz')], max_length=20, null=True, verbose_name='Taux de rafraîchissement'),
        ),
    ]
