# Generated by Django 6.0.6 on 2026-07-09 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_productvariant_taux_rafraichissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500, verbose_name="URL de l'image")),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Image de variante',
                'verbose_name_plural': 'Images de variante',
                'ordering': ['ordre'],
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
