# Generated by Django 6.0.6 on 2026-07-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_variantimage_delete_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
