# Generated by Django 6.0.6 on 2026-07-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_product_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='layout_type',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Paysage')], default='portrait', max_length=20, verbose_name="Type d'affichage"),
        ),
    ]
