# Generated by Django 6.0.6 on 2026-07-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_avisclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note_etat_occasion',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Requis si l'état est 'Occasion'. Note de 1 à 10.", null=True, verbose_name="Note de l'état (sur 10)"),
        ),
    ]
