# Generated by Django 6.0.6 on 2026-07-22 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_favori'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Type de mouvement')),
                ('motif', models.CharField(max_length=100, verbose_name='Motif')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='shop.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
    ]
