# Generated by Django 6.0.6 on 2026-07-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie de charge',
                'verbose_name_plural': 'Catégories de charges',
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat fournisseur (FCFA)"),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='shop.expensecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Charge / Dépense',
                'verbose_name_plural': 'Charges / Dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
