# Generated by Django 6.0.6 on 2026-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_expensecategory_productvariant_prix_achat_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='statut_publication',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut de publication'),
        ),
    ]
