# Generated by Django 6.0.6 on 2026-07-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_product_statut_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['created_at', 'produit', 'couleur', 'ram', 'stockage'], 'verbose_name': 'Variante produit', 'verbose_name_plural': 'Variantes produit'},
        ),
    ]
