# Generated by Django 6.0.6 on 2026-07-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_add_employee_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Poste / Fonction'),
        ),
    ]
