// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1jB8KSZHMBmU1Z41MaflU80TK9K4tcSM',
    appId: '1:604730974010:web:c8ce2af692d25042063a03',
    messagingSenderId: '604730974010',
    projectId: 'sansgato-2876e',
    authDomain: 'sansgato-2876e.firebaseapp.com',
    storageBucket: 'sansgato-2876e.firebasestorage.app',
    measurementId: 'G-ZNNBFJCS7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDneiYbHr-167F9ChGyY3BcUP6PsTz4MlQ',
    appId: '1:604730974010:android:e34f1144bf5e6b94063a03',
    messagingSenderId: '604730974010',
    projectId: 'sansgato-2876e',
    storageBucket: 'sansgato-2876e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqNysHbvbaFmVu-AKQfhlF-DU2ZmHPEhE',
    appId: '1:604730974010:ios:f1960bd5719f2968063a03',
    messagingSenderId: '604730974010',
    projectId: 'sansgato-2876e',
    storageBucket: 'sansgato-2876e.firebasestorage.app',
    androidClientId: '604730974010-hepesf13l1t6f99og9vtrciedfbta9ke.apps.googleusercontent.com',
    iosClientId: '604730974010-bjio51aj7tpa4mh6l2s1epfk7lg3rrkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.sansgato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqNysHbvbaFmVu-AKQfhlF-DU2ZmHPEhE',
    appId: '1:604730974010:ios:f1960bd5719f2968063a03',
    messagingSenderId: '604730974010',
    projectId: 'sansgato-2876e',
    storageBucket: 'sansgato-2876e.firebasestorage.app',
    androidClientId: '604730974010-hepesf13l1t6f99og9vtrciedfbta9ke.apps.googleusercontent.com',
    iosClientId: '604730974010-bjio51aj7tpa4mh6l2s1epfk7lg3rrkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.sansgato',
  );
}
