# Generated by Django 6.0.6 on 2026-07-12 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0022_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('especes', 'Espèces (à la livraison)')], default='mobile_money', max_length=20, verbose_name='Méthode de paiement')),
                ('payment_status', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut du paiement')),
                ('transaction_id', models.CharField(blank=True, help_text="ID renvoyé par l'API de paiement", max_length=100, null=True, verbose_name='ID de transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date mise à jour')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
